---
title: "Amostra alunos CCC x PPGCC"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
theme_set(theme_bw())

library(broom)

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5)

```

```{r read}
dados = read_csv(here::here("data/amostra-alunos-comfpcc.csv"))

dados = dados %>%
    rename(
        sono_semana = `Quantas horas por noite você dorme DURANTE A SEMANA em média?`,
        sono_fds = `Quantas horas por noite você dorme durante NO FIM DE SEMANA em média?`,
        disciplinas = `Quantas disciplinas você está cursando esse semestre?`,
        cafe = `Quantas xícaras de café você tomou ontem?`,
        segue_gh = `Quantas pessoas você segue no github?`,
        seguido_gh = `Quantas pessoas seguem você no github?`,
        quase_concluinte = `Você está dois períodos ou menos de concluir?`
    )

dados = dados %>% 
    mutate(data = lubridate::mdy_hms(Timestamp),
           turma = if_else(data < as.POSIXct("2019-05-24 12:00:00"), 
                           "cdd", 
                           "fpcc"))%>% 
    filter(segue_gh < 800, 
           disciplinas < 10,
           seguido_gh < 900)


glimpse(dados)
```

```{r}
dados %>% 
    ggplot(aes(x = sono_semana)) + 
    geom_histogram(binwidth = 1, boundary = 0) + 
    facet_wrap(~ turma, 
               ncol = 1)

dados %>% 
    ggplot(aes(x = sono_fds)) + 
    geom_histogram(binwidth = 1, boundary = 0) + 
    facet_wrap(~ turma, 
               ncol = 1) + 
    xlim(5, 10)
```

```{r}
dados %>% 
    group_by(turma) %>% 
    summarise(media_semana = mean(sono_semana), 
              media_fds = mean(sono_fds), 
              sd_semana = sd(sono_semana), 
              sd_fds = sd(sono_fds))
```


## Com ICs

### FDS

```{r}
theta_diferenca_fds = function(d, i){
    sonos = d %>% 
        slice(i) %>% 
        group_by(turma) %>% 
        summarise(sono = mean(sono_fds)) 
    
    cdd = sonos %>% filter(turma == "cdd") %>% pull(sono)
    fpcc = sonos %>% filter(turma == "fpcc") %>% pull(sono)
    
    cdd - fpcc
}


theta_c_fds = theta_diferenca_fds(dados, 1:NROW(dados))

theta_c_fds
```

```{r}
library(boot)
dados %>% 
    boot(statistic = theta_diferenca, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```

### Semana


```{r}
theta_diferenca_semana = function(d, i){
    sonos = d %>% 
        slice(i) %>% 
        group_by(turma) %>% 
        summarise(sono = mean(sono_semana)) 
    
    cdd = sonos %>% filter(turma == "cdd") %>% pull(sono)
    fpcc = sonos %>% filter(turma == "fpcc") %>% pull(sono)
    
    cdd - fpcc
}


theta_diferenca_semana(dados, 1:NROW(dados))
```

```{r}
dados %>% 
    boot(statistic = theta_diferenca, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```

